Tracker:AddLocations("locations/Ancient Pyramid.json")
Tracker:AddLocations("locations/Castle Basement.json")
Tracker:AddLocations("locations/Castle Keep.json")
Tracker:AddLocations("locations/Castle Ramparts.json")
Tracker:AddLocations("locations/Caves of Banishment (Maw).json")
Tracker:AddLocations("locations/Caves of Banishment (Sirens).json")
Tracker:AddLocations("locations/Emperor's Tower.json")
Tracker:AddLocations("locations/Forest.json")
Tracker:AddLocations("locations/Ifrit.json")
Tracker:AddLocations("locations/Lab.json")
Tracker:AddLocations("locations/Lake Desolation.json")
Tracker:AddLocations("locations/Lake Desolation (Lower).json")
Tracker:AddLocations("locations/Lake Desolation (Upper).json")
Tracker:AddLocations("locations/Lake Serene.json")
Tracker:AddLocations("locations/Lake Serene (Lower).json")
Tracker:AddLocations("locations/Lake Serene (Upper).json")
Tracker:AddLocations("locations/Library.json")
Tracker:AddLocations("locations/Military Fortress.json")
Tracker:AddLocations("locations/Ravenlord.json")
Tracker:AddLocations("locations/Refugee Camp.json")
Tracker:AddLocations("locations/Royal Towers.json")
Tracker:AddLocations("locations/Sealed Caves (Sirens).json")
Tracker:AddLocations("locations/Sealed Caves (Xarion).json")
Tracker:AddLocations("locations/Temporal Gyre.json")
Tracker:AddLocations("locations/Tutorial.json")
Tracker:AddLocations("locations/Varndagroth Towers.json")
Tracker:AddLocations("locations/Varndagroth Towers (Left).json")
Tracker:AddLocations("locations/Varndagroth Towers (Right).json")
Tracker:AddLocations("locations/Overworld.json")
